name: ChristmasGift
version: '1.0'
main: com.resistancecore.christmasgift.ChristmasGift
api-version: '1.21'
author: ResistanceCore
description: Christmas gift plugin with tier system and special effects
commands:
  christmasgift:
    description: Main command for ChristmasGift plugin
    usage: |
      /<command> - Open admin GUI (player only)
      /<command> give <amount> [player] - Give Christmas gifts
      /<command> reload - Reload configuration
    aliases: [cgift, xmasgift]
    permission: christmasgift.admin
    permission-message: §c§lChristmasGift §7» §cYou don't have permission to use this command!

permissions:
  christmasgift.admin:
    description: Permission to use ChristmasGift admin commands
    default: op
